# Generated by Django 2.1.7 on 2019-03-04 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_room', '0002_auto_20190304_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='data',
            new_name='date',
        ),
    ]
